dist: xenial
language: python
sudo: true
addons:
  postgresql: '10'
  apt:
    packages:
      - postgresql-10-postgis-2.4
      - postgresql-10-postgis-2.4-scripts
      - postgresql-client-10


matrix:
    fast_finish: true
    include:

      - { python: "3.8", env: DJANGO_VERSION=3.2.12 }
      - { python: "3.8", env: DJANGO_VERSION=4.0.3 }

      - { python: "3.9", env: DJANGO_VERSION=3.2.12 }
      - { python: "3.9", env: DJANGO_VERSION=4.0.3 }

      - { python: "3.10", env: DJANGO_VERSION=3.2.12 }
      - { python: "3.10", env: DJANGO_VERSION=4.0.3 }


before_install:
  - sudo -u postgres psql -c "CREATE USER testuser WITH PASSWORD 'password'"
  - sudo -u postgres psql -c "ALTER ROLE testuser SUPERUSER"

install:
  - pip install coverage
  - pip install coveralls
  - pip install -q Django==$DJANGO_VERSION
  - pip install psycopg2

before_script:
  - psql -U postgres -c "create extension postgis"
script:
  - coverage run --source=mapbox_location_field manage.py test
after_success:
  - coveralls